services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8888:8888"

    restart: unless-stopped

    environment:
      DATABASE_URL: "postgresql://postgres:euroasiann1234@72.61.236.117:5432/postgres?sslmode=require"

    command: sh ./entrypoint.sh

